keys, values = keysAndValues({d: 4, e: 5, f: 6, g: 7})
Test.expect(keys, 'function did not return keys')
Test.expect(values, 'function did not return values')
Test.expect(keys.length == 4, 'function did not return enough keys')
Test.expect(values.length == 4, 'function did not return enough values')
Test.expect(keys[1] == :e, 'function did not return correct keys')
Test.expect(values[2] == 6, 'function did not return correct values')
